Support claim attribute mappings in bulk
wso2/identity-api-server pull request #299
Opened 2021-08-06 11:13 UTC by Thisara-Welmilla

Related issue:
- https://github.com/wso2/product-is/issues/12253

Implementation changes
- Modify https://is.docs.wso2.com/en/latest/develop/userstore-rest-api/#/User%20Store `/userstores` API to support claim attribute mappings in bulk at user store creation.
- Introduce a new API to update the claim attribute mapping in bulk for a specific user store.

2021-08-11 06:47 UTC, JKAUSHALYA requested changes

2021-08-12 09:55 UTC, Thisara-Welmilla commented on components/org.wso2.carbon.identity.api.server.userstore/org.wso2.carbon.identity.api.server.userstore.common/src/main/java/org/wso2/carbon/identity/api/server/userstore/common/UserStoreConfigServiceHolder.java
> +        return UserStoreConfigServiceHolder.getInstance().claimMetadataManagementService;
As this class is a singleton, the `UserStoreConfigServiceHolder.getInstance()` refers to a static intance. therefore have implement in this way.

2021-08-12 09:55 UTC, Thisara-Welmilla commented on components/org.wso2.carbon.identity.api.server.userstore/org.wso2.carbon.identity.api.server.userstore.common/src/main/java/org/wso2/carbon/identity/api/server/userstore/common/UserStoreConfigServiceHolder.java
> +        UserStoreConfigServiceHolder.getInstance().claimMetadataManagementService = claimMetadataManagementService;
As this class is a singleton, the `UserStoreConfigServiceHolder.getInstance()` refers to a static intance. therefore have implement in this way.

2021-08-12 09:56 UTC, Thisara-Welmilla commented on components/org.wso2.carbon.identity.api.server.userstore/org.wso2.carbon.identity.api.server.userstore.common/src/main/java/org/wso2/carbon/identity/api/server/userstore/common/factory/ClaimMetadataManagementServiceFactory.java
> +        if (this.claimMetadataManagementService == null) {
Addressed with commit 734474d456011dc9caf613a1a7a0f9876f511247

2021-08-13 13:15 UTC, Thisara-Welmilla commented
Reopened with https://github.com/wso2/identity-api-server/pull/301

2021-08-13 13:15 UTC, closed without merging